import React,{ useState } from "react";
import "./App.css";

function App() {
  const [students] = useState([
      { id: 1, name: "Arjun", session: "React Basics", status: "Present" },
          { id: 2, name: "Priya", session: "React Basics", status: "Absent" },
              { id: 3, name: "Karthik", session: "API Handling", status: "Present" },
                  { id: 4, name: "Meena", session: "API Handling", status: "Present" },
                      { id: 5, name: "Ravi", session: "React Basics", status: "Absent" },
                          { id: 6, name: "Sneha", session: "API Handling", status: "Absent" }
                            ]);

                              const [filter, setFilter] = useState("All");

                                // Filter logic - Module 4 concept da
                                  const filteredStudents = filter === "All"
                                     ? students
                                         : students.filter(s => s.status === filter);

                                           // Stats calculate panradhu
                                             const total = students.length;
                                               const present = students.filter(s => s.status === "Present").length;
                                                 const absent = total - present;

                                                   return (
                                                       <div className="dashboard">
                                                             <h1>Trainer Session Attendance</h1>

                                                                   {/* Dashboard Cards */}
                                                                         <div className="stats">
                                                                                 <div className="card total">
                                                                                           <h3>Total Students</h3>
                                                                                                     <p>{total}</p>
                                                                                                             </div>
                                                                                                                     <div className="card present">
                                                                                                                               <h3>Present</h3>
                                                                                                                                         <p>{present}</p>
                                                                                                                                                 </div>
                                                                                                                                                         <div className="card absent">
                                                                                                                                                                   <h3>Absent</h3>
                                                                                                                                                                             <p>{absent}</p>
                                                                                                                                                                                     </div>
                                                                                                                                                                                           </div>

                                                                                                                                                                                                 {/* Filter Buttons - Conditional Rendering ku use aagum */}
                                                                                                                                                                                                       <div className="filters">
                                                                                                                                                                                                               <button onClick={() => setFilter("All")} className={filter==="All"?"active":""}>All</button>
                                                                                                                                                                                                                       <button onClick={() => setFilter("Present")} className={filter==="Present"?"active":""}>Present</button>
                                                                                                                                                                                                                               <button onClick={() => setFilter("Absent")} className={filter==="Absent"?"active":""}>Absent</button>
                                                                                                                                                                                                                                     </div>

                                                                                                                                                                                                                                           {/* Student Table - Conditional Rendering idhu dhan da */}
                                                                                                                                                                                                                                                 {filteredStudents.length > 0? (
                                                                                                                                                                                                                                                         <table>
                                                                                                                                                                                                                                                                   <thead>
                                                                                                                                                                                                                                                                               <tr>
                                                                                                                                                                                                                                                                                             <th>ID</th>
                                                                                                                                                                                                                                                                                                           <th>Name</th>
                                                                                                                                                                                                                                                                                                                         <th>Session</th>
                                                                                                                                                                                                                                                                                                                                       <th>Status</th>
                                                                                                                                                                                                                                                                                                                                                   </tr>
                                                                                                                                                                                                                                                                                                                                                             </thead>
                                                                                                                                                                                                                                                                                                                                                                       <tbody>
                                                                                                                                                                                                                                                                                                                                                                                   {filteredStudents.map(student => (
                                                                                                                                                                                                                                                                                                                                                                                                 <tr key={student.id} className={student.status.toLowerCase()}>
                                                                                                                                                                                                                                                                                                                                                                                                                 <td>{student.id}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                 <td>{student.name}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                 <td>{student.session}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <span className={`badge ${student.status.toLowerCase()}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       {student.status}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             </tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   // Idhu dhan Conditional Rendering da macha
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           <div className="no-data">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     <h2>No students found for "{filter}" status</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               <p>Please select "All" to view all students</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   export default App;
